//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsServiceTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Skipped!! - Run this command in an administrative command prompt.
        /// </summary>
        internal static string CommandAdminElevationError {
            get {
                return ResourceManager.GetString("CommandAdminElevationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Access Level - Administrative privileges required.
        /// </summary>
        internal static string CommandAdminElevationException {
            get {
                return ResourceManager.GetString("CommandAdminElevationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Skipped!! - Service not installed.
        /// </summary>
        internal static string CommandUninstallServiceMissingError {
            get {
                return ResourceManager.GetString("CommandUninstallServiceMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSTLog.
        /// </summary>
        internal static string EventLogName {
            get {
                return ResourceManager.GetString("EventLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src.
        /// </summary>
        internal static string EventLogSourceSuffix {
            get {
                return ResourceManager.GetString("EventLogSourceSuffix", resourceCulture);
            }
        }
    }
}
